Live coding 1 #01 11 2020
KuzniaCo/TodoApp-Api pull request #3
Opened 2020-11-02 12:26 UTC by Vengardd

2020-11-02 18:22 UTC, jwalaszek approved these changes

2020-11-02 19:30 UTC, tadeuszcirocki requested changes
piękne

2020-11-02 19:30 UTC, tadeuszcirocki commented on src/main/java/pl/ug/kuznia/todoappapi/internal/card/CardController.java
> +    @PostMapping("/add")
![image](https://user-images.githubusercontent.com/45399049/97910329-e19e5400-1d49-11eb-8d20-a872127bf637.png)
?

2020-11-02 20:07 UTC, kkulewski commented on src/main/java/pl/ug/kuznia/todoappapi/internal/card/CardController.java
> +    @PostMapping("/add")
100% agree

2020-11-02 23:47 UTC, Vengardd commented on src/main/java/pl/ug/kuznia/todoappapi/internal/card/CardController.java
> +    @PostMapping("/add")
completely forget about looking at it xD 
Thanks!

2020-11-07 11:12 UTC, Vengardd commented on src/main/java/pl/ug/kuznia/todoappapi/internal/card/CardController.java
> +    @PostMapping("/add")
Done

2020-11-07 13:25 UTC, bartlomiejmont approved these changes

2020-11-07 22:45 UTC, tadeuszcirocki approved these changes

2020-11-08 18:31 UTC, kkulewski approved these changes

2020-11-08 22:32 UTC, Nicofisi requested changes
Looks fine overall!

2020-11-08 22:32 UTC, Nicofisi commented on build.gradle
> +    compile group: 'org.hibernate', name: 'hibernate-validator', version: '6.1.6.Final'
It would be good to use the same format as above
```suggestion
    implementation 'org.hibernate:hibernate-validator:6.1.6.Final'
```

2020-11-09 09:33 UTC, merged